name: pedattr39
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.9.25
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aistudio-sdk==0.3.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==25.4.0
      - bce-python-sdk==0.9.54
      - beautifulsoup4==4.14.2
      - cachetools==6.2.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - chinese-calendar==1.11.0
      - click==8.1.8
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.0
      - cssselect==1.3.0
      - cssutils==2.11.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - decord==0.6.0
      - distro==1.9.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - faiss-cpu==1.13.0
      - filelock==3.19.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - gputil==1.4.0
      - greenlet==3.2.4
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.1.6
      - idna==3.11
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - langchain==0.3.27
      - langchain-community==0.3.31
      - langchain-core==0.3.80
      - langchain-openai==0.3.35
      - langchain-text-splitters==0.3.11
      - langsmith==0.4.37
      - lazy-loader==0.4
      - lxml==6.0.2
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - modelscope==1.32.0
      - more-itertools==10.8.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - numpy==2.0.2
      - openai==2.8.1
      - opencv-contrib-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - orjson==3.11.4
      - packaging==25.0
      - paddlepaddle==3.0.0
      - paddlex==3.3.10
      - pandas==2.3.3
      - pillow==11.1.0
      - premailer==3.10.0
      - prettytable==3.16.0
      - propcache==0.4.1
      - protobuf==6.30.2
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyclipper==1.3.0.post6
      - pycocotools==2.0.8
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.11.0
      - pyparsing==3.2.5
      - pypdfium2==5.1.0
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentencepiece==0.2.1
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
